#pragma config(Sensor, in1,    Potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port1,           armMotor1,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           armMotor2,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{
		if(vexRT[Btn7U] == 1)
			if(SensorValue[Potentiometer]

}
}
