
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, I2C_1,  frontIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  backIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           thing1top,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           wristmotorl,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armMotor2,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           wristmotorr,   tmotorVex393, openLoop)
#pragma config(Motor,  port7,           frontMotor,    tmotorVex269, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port8,           backMotor,     tmotorVex269, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port9,           leftMotor,     tmotorVex269, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269, openLoop, encoder, encoderPort, I2C_4, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{

	bStopTasksBetweenModes = true;

	nMotorEncoder[rightMotor] = 0;
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[frontMotor] = 0;
	nMotorEncoder[backMotor] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	motor[thing1top] = 127;
	motor[wristmotorr] = -127;
	motor[wristmotorl] = -127;
	wait1Msec(1000);
	motor[thing1top] = 0;
	motor[wristmotorl] = 0;
	motor[wristmotorr] = 0;
	SensorValue[I2C_1] = 0;
	SensorValue[I2C_2] = 0;
	SensorValue[I2C_3] = 0;
	SensorValue[I2C_4] = 0;


	while((SensorValue[I2C_2] <= 10) && (SensorValue[I2C_4] <= 10))
	{
		motor[leftMotor] = 63;
		motor[rightMotor] = 63;
		motor[frontMotor] = 0;
		motor[backMotor] = 0;
	}
	while((SensorValue[I2C_2] >= 10)&&(SensorValue[I2C_4] >= 10))
	{
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		motor[backMotor] = 0;
		motor[frontMotor] = 0;
	}
	wait1Msec(1000);
	while(SensorValue[Potentiometer] >= 3530)
	{
		motor[armMotor] = -100;
		motor[armMotor2] = -100;
	}
	while(SensorValue[Potentiometer] <= 2055)
	{
		motor[armMotor] = 0;
		motor[armMotor2] = 0;
	}
	wait1Msec(500);
	motor[wristmotorl] =2; //find value later
	motor[wristmotorr] = 2;//find value later
	motor[thing1top] = -100;
	SensorValue[I2C_1] = 0;
	SensorValue[I2C_3] = 0;
	while((SensorValue[I2C_2] <= 10)&&(SensorValue[I2C_4]<= 10))
	{
		motor[rightMotor] = -63;
		motor[leftMotor]  = -63;
	}

	while((SensorValue[I2C_2] >= 10) && (SensorValue[I2C_4]>= 10))
	{
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
		if(vexRT[Btn7U] == 1)
		{
			motor[armMotor] = -127;
			motor[armMotor2] = -127;
		}
		else if(vexRT[Btn7D] == 1)
		{
			motor[armMotor] = 127;
			motor[armMotor2] = 127;
		}
		else
		{
			motor[armMotor] = 0;
			motor[armMotor2] = 0;
		}

		if(vexRT[Btn5U]==1)
		{
			motor[thing1top] = -127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[thing1top] = 127;
		}
		else
		{
			motor[thing1top] = 0;
		}

		if (vexRT[Btn6U] == 1)
		{
			motor[wristmotorl] = -127;
			motor[wristmotorr] = -127;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[wristmotorl] = 127;
			motor[wristmotorr] = 127;
		}
		else
		{
			motor[wristmotorl] = 0;
			motor[wristmotorr] = 0;
		}

		if( vexRT[Ch4] == 0)
		{
			int iCh2 = vexRT[Ch2];
			int iCh1 = vexRT[Ch1];
			if(vexRT[Ch1] > -15 && vexRT[Ch1] < 15)
			{
				iCh1= 0;
			}
			bMotorReflected[rightMotor] = false;
			bMotorReflected[leftMotor] = true;
			bMotorReflected[frontMotor] = false;
			bMotorReflected[backMotor] = true;

			motor[frontMotor] = iCh1;
			motor[backMotor] = iCh1;
			motor[rightMotor] = iCh2;
			motor[leftMotor] = iCh2;
		}
		else
		{
			bMotorReflected[rightMotor] = true;
			bMotorReflected[leftMotor] = true;
			bMotorReflected[backMotor] = false;
			bMotorReflected[frontMotor] = false;
			motor[rightMotor] = vexRT[Ch4];
			motor[leftMotor] = vexRT[Ch4];
			motor[backMotor] = vexRT[Ch4];
			motor[frontMotor] = vexRT[Ch4];

		}

	}
}
