#pragma config(Sensor, in1,    Potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port1,           thing1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor2,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           thing2,        tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{

		if(vexRT[Btn6U] == 1)
		{
			motor[armMotor] = -50;
			motor[armMotor2] = -50;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = 50;
			motor[armMotor2] = 50;
		}
		else if(vexRT[Btn7U]==1)
		{
			motor[thing1] = 50;
			motor[thing2] = -50;
		}
		else if (vexRT[Btn7D])
		{
			motor[thing1] = -50;
			motor[thing2] = 50;
		}
		else
		{
			motor[armMotor2] = 0;
			motor[armMotor] = 0;
			motor[thing1] = 0;
			motor[thing2] = 0;
		}


	}
}
