#pragma config(Sensor, in1,    yoyo,           sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	while (true)

	{


		bMotorReflected[port1] = false;
		bMotorReflected[port2] = true;
		bMotorReflected[port7] = false;
		bMotorReflected[port10] = true;

		if (SensorValue[yoyo] <= 600)
	{	motor[port1] = 127;//left
		motor[port2] = 127;
		motor[port7] = -127;
		motor[port10] = -127;
	}
			else if (SensorValue[yoyo] >= 2500)
	{	motor[port1] = -127;
		motor[port2] = -127;
		motor[port7] = 127;
		motor[port10] = 127;
	}
				else
	{	motor[port1] = 127;
		motor[port2] = 127;
		motor[port7] = 127;
		motor[port10] = 127;

}

}}
