#pragma config(Sensor, dgtl1,  MotorSensor,    sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
wait1Msec(2000);
SensorValue[MotorSensor] = 0;
while(SensorValue[MotorSensor] < 500)
	{
		motor[port10] = 63;


}
