
task main()
{
#pragma config(Motor, port2, LeftTop, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port3, RightTop, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port8, RightBack, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port9, LeftBack, tmotorServoContinuousRotation, openLoop)
	//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//


	int joy_x;
	int joy_y;
	int rot;

	int m1 = 0;
	int m2 = 0;
	int m3 = 0;
	int m4 = 0;

	while(1)
	{
		joy_x = vexRT[Ch2];
		joy_y = vexRT[Ch4];
		rot = vexRT[Ch1];

		m1 = (joy_y) + (-1 * joy_x) + (-1 * rot);
		m2 = (-1 * joy_y) + (-1 * joy_x) + (-1 * rot);
		m3 = (-1 * joy_y) + (joy_x) + (-1 * rot);
		m4 = (joy_y) + (joy_x) + (-1 * rot);

		if (m1 >= 127)
		{
			m1 = 127;
		}
		else if (m1 <= -127)
		{
			m1 = -127;
		}

		if (m2 >= 127)
		{
			m2 = 127;
		}
		else if (m2 <= -127)
		{
			m2 = -127;
		}

		if (m3 >= 127)
		{
			m3 = 127;
		}
		else if (m3 <= -127)
		{
			m3 = -127;
		}

		if (m4 >= 127)
		{
			m4 = 127;
		}
		else if (m4 <= -127)
		{
			m4 = -127;
		}

		motor[port2] = m1;
		motor[port3] = m2;
		motor[port8] = m3;
		motor[port9] = m4;
	}
}
