#pragma config(Sensor, in1,    LineTracker1,   sensorLineFollower)
#pragma config(Sensor, in2,    LineTrack2,     sensorLineFollower)
#pragma config(Sensor, in3,    potent1,        sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(2000);          // The program waits for 2000 milliseconds before continuing.

  int threshold = 1500;    /* found by taking a reading on both DARK and LIGHT    */
                           /* surfaces, adding them together, then dividing by 2. */

  ClearTimer(T1);						// Resets timer T1 to start counting at 0

	while(time1[T1] < 10000)  // Loops code while timer T1 has counted less than 10 seconds
  {

}




}
