#pragma config(Motor,  port9,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

  while(true)
  {

		if (SensorValue(potentiometer)< 1000)
		{
			motor[armMotor]=-20 ;
		}
		 else if (SensorValue(potentiometer)> 1100)
		{
			motor[armMotor]=20 ;
	  }
		else
		{
			motor[armMotor]=0 ;
		}

  }
}
