#pragma config(Motor,  port2,           potato,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           goawayryan,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()

{


motor[goawayryan] = -1000 ;


	wait1Msec(1000) ;

	motor[goawayryan] = 1000 ;

	wait1Msec(3000) ;

}
