#pragma config(Sensor, dgtl1,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  right,          sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){

	bMotorReflected[port1] = false;
	bMotorReflected[port10] = true;
	bMotorReflected[port2] = true;
	bMotorReflected[port9] = false;

	motor[port1] = 127;
	motor[port2] = 127;
	motor[port9] = 127;
	motor[port10] = 127;
}




}
