#pragma config(Sensor, in1,    teamSwitchPot,  sensorPotentiometer)
#pragma config(Sensor, in2,    forkLiftPot,    sensorPotentiometer)
#pragma config(Sensor, dgtl11, liftHeight,     sensorQuadEncoder)
#pragma config(Motor,  port2,           liftPair1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftPair2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           deployClaw,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           rightTrack,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftTrack,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(bool,  port8,						teamSwitch,
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#define HOLD_POWER 30
#define LIFT_PRESET_HEIGHT_LOW 10
#define LIFT_PRESET_HEIGHT_MID 248
#define LIFT_PRESET_HEIGHT_HIGH 444
#define LIFT_PRESET_HEIGHT_MAX 600

#define LIFT_PRESET_HEIGHT_LOW_FORK_DOWN 10
#define LIFT_PRESET_HEIGHT_LOW_FORK_UP 10

#define LIFT_PRESET_HEIGHT_MID_FORK_UP 248
#define LIFT_PRESET_HEIGHT_MID_FORK_DOWN 300

#define LIFT_PRESET_HEIGHT_HIGH_FORK_UP 444
#define LIFT_PRESET_HEIGHT_HIGH_FORK_DOWN 500

#define FORK_PRESET_UP 500
#define FORK_PRESET_DOWN 500

enum preset{low, mid, high};
enum position{up, down};
enum mode{manual, automatic};

//prototypes
void initLiftHeight();

//globals
bool teamSwitch;

//teamSwitch = true;
void pre_auton()
{
}

//true is for blue, false is for red.
//between 708 and 4095

task autonomous()
{
	//lift1 range shd be 0 to 656
// lift shd be lowered prior to autonomous routine starting
//there will be a separate control for the fork lift
//SensorValue[liftHeight] = 0;
if(SensorValue[teamSwitchPot] > 2350)
{
 	teamSwitch = true;
}
	else
{
		teamSwitch = false;
}




//auto Blue
	if( teamSwitch == true){
 		//lift up body
		motor[liftPair1] = -40;
  	motor[liftPair2] = -40;
  	sleep(750);
		motor[liftPair1] = 0;
  	motor[liftPair2] = 0;

		//deploy claw
  	motor[claw] = -127;
  	sleep(3000);
  	motor[claw] = 0;

 		//lower body
 		motor[liftPair1] = 40;
 		motor[liftPair2] = 40;
 		sleep(750);
 		motor[liftPair1] = 0;
 		motor[liftPair2] = 0;

  	//move forward
		motor[rightTrack] = 60;
		motor[leftTrack] = 60;
		sleep(2100);
		motor[rightTrack] = 0;
		motor[leftTrack] = 0;

		//turn right
		motor[rightTrack] = -60;
		motor[leftTrack] = 60;
		sleep(1800);
		motor[rightTrack] = 0;
		motor[leftTrack] = 0;

		//to flag
		motor[rightTrack] = 60;
		motor[leftTrack] = 60;
		sleep(2800);
		motor[rightTrack] = 0;
		motor[leftTrack] = 0;
	}
	//auto Red
	//if( teamSwitch == false){
	else{
		//lift up
		motor[liftPair1] = -40;
	  motor[liftPair2] = -40;
	  sleep(750);
		motor[liftPair1] = 0;
	  motor[liftPair2] = 0;

		//deploy claw
	  motor[claw] = -127;
	  sleep(3000);
	  motor[claw] = 0;

	 	//lower
	 	motor[liftPair1] = 40;
	 	motor[liftPair2] = 40;
	 	sleep(700);
	 	motor[liftPair1] = 0;
	 	motor[liftPair2] = 0;

	  //move forward
		motor[rightTrack] = 60;
		motor[leftTrack] = 60;
		sleep(2050);
		motor[rightTrack] = 0;
		motor[leftTrack] = 0;

		//turn left
		motor[rightTrack] = 60;
		motor[leftTrack] = -60;
		sleep(900);
		motor[rightTrack] = 0;
		motor[leftTrack] = 0;

		//to flag
		motor[rightTrack] = 60;
		motor[leftTrack] = 60;
		sleep(2900);
		motor[rightTrack] = 0;
		motor[leftTrack] = 0;

	}
}
 //end autonomous


/////////////////////////////////////////////////////////////////////////////////////////
//
// initLiftHeight
//
// Initializes the liftHeight sensor by moving down the lift and checking the value of
// the sensor until it doesn't change anymore
//
/////////////////////////////////////////////////////////////////////////////////////////
void initLiftHeight()
{
	writeDebugStreamLine("initLiftHeight");
	bool done = false;
	int current_position = 0;
	int previous_position = 0;
	int diff;
	int liftPower;
	while(!done)
	{
		previous_position = SensorValue[liftHeight];

		liftPower = 40;
		motor[liftPair1] = liftPower;
		motor[liftPair2] = liftPower;
		sleep(250);
		liftPower = 0;
		motor[liftPair1] = liftPower ;
		motor[liftPair2] = liftPower ;

		current_position = SensorValue[liftHeight];
		diff = abs(previous_position) - abs(current_position);
		writeDebugStreamLine("comparing: %d -- %d [%d]", previous_position,current_position,abs(diff));
		if(abs(diff) <= 1)
		{
			done = true;
			//SensorValue[liftHeight] = 0;
		}
	}
	sleep(250);
	SensorValue[liftHeight] = 0;

}


/////////////////////////////////////////////////////////////////////////////////////////
//
//																 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
task usercontrol()
{
	bool partnerMode = true;
	int power = 0;
	int liftValue = 0;
	int clawDrive = 0;
	int count = 0;
	int targetHeightValue = 0;
	bool upLiftPresetLock = false;
	bool downLiftPresetLock = false;
	int diff;
	enum preset liftPreset;
	enum mode liftMode; //{manual,preset}

	//init lift height
	initLiftHeight();
	//init lift preset value
	liftPreset = low;

	while(1)
	{
		//writeDebugStreamLine("pot value: %d", SensorValue[teamSwitchPot]);
		//writeDebugStreamLine("pot value: %d", SensorValue[forkLiftPot]);

		//select partner or user mode
		if((vexRT[Btn7R] == 1)&&(vexRT[Btn7L] == 1)&&(partnerMode == true))
		{
			count = count + 1;
			//writeDebugStreamLine("count %d", count);
			if(count > 200)
			{
				motor[claw] = 50;
				sleep(50);
				motor[claw] = 0;
				sleep(50);
				partnerMode = false;
				writeDebugStreamLine("solo %d", count);
				count = 0;
			}
		}
		else if ((vexRT[Btn7R] == 1)&&(vexRT[Btn7L] == 1)&&(partnerMode == false))
		{
			count = count + 1;
			//writeDebugStreamLine("count %d", count);
			if(count > 200)
			{
				motor[claw] = -50;
				sleep(50);
				motor[claw] = 50;
				sleep(50);
				motor[claw] = -50;
				sleep(50);
				motor[claw] = 50;
				sleep(50);
				motor[claw] = 0;
				sleep(50);
				partnerMode = true;
				writeDebugStreamLine("partner %d", count);
				count = 0;
			}
		}

		if(partnerMode)
		{
			//drive
			motor[rightTrack] = vexRT[Ch2];
			motor[leftTrack] = vexRT[Ch3];

			////////////////////////////////////////////////////

			//lift progressive power
			if((vexRT[Btn5UXmtr2] == 1)||(vexRT[Btn5DXmtr2] == 1))
			{
				liftMode = manual;
				if(power < 126)
				{
					power = power + 2;
				}
			}
			//writeDebugStreamLine("power %d", power);

			//lift
			if((vexRT[Btn5UXmtr2] == 1)&&(liftMode == manual))
			{
				liftValue = power * -1;
			}
			else if((vexRT[Btn5DXmtr2] == 1)&&(liftMode == manual))
			{
				liftValue = power;
			}
			else
			{
				liftValue = 0;
				power = 0;
			}

			//##################################################################################
			//lift preset
			//writeDebugStreamLine("liftPreset %d", liftPreset);
			if(vexRT[Btn7UXmtr2] == 0)
			{
				upLiftPresetLock = false;
			}
			if(vexRT[Btn7DXmtr2] == 0)
			{
				downLiftPresetLock = false;
			}

			//lift mode
			if((vexRT[Btn7UXmtr2] == 1)||(vexRT[Btn7DXmtr2] == 1))
			{
				liftMode = automatic;
			}
			//low to mid
			if((vexRT[Btn7UXmtr2] == 1)&&(liftPreset == low)&&(upLiftPresetLock == false))
			{
				liftPreset = mid;
				upLiftPresetLock = true;
			}
			//mid to high
			else if((vexRT[Btn7UXmtr2] == 1)&&(liftPreset == mid)&&(upLiftPresetLock == false))
			{
				liftPreset = high;
				upLiftPresetLock = true;
			}
			//high to mid
			else if((vexRT[Btn7DXmtr2] == 1)&&(liftPreset == high)&&(downLiftPresetLock == false))
			{
				liftPreset = mid;
				downLiftPresetLock = true;
			}
			//mid to low
			else if((vexRT[Btn7DXmtr2] == 1)&&(liftPreset == mid)&&(downLiftPresetLock == false))
			{
				liftPreset = low;
				downLiftPresetLock = true;
			}

			//set lift motor values
			switch (liftPreset)
			{
				case low: 	targetHeightValue = LIFT_PRESET_HEIGHT_LOW;
		               	break;
				case mid: 	targetHeightValue = LIFT_PRESET_HEIGHT_MID;
		               	break;
				case high: 	targetHeightValue = LIFT_PRESET_HEIGHT_HIGH;
		               	break;
				default:		targetHeightValue = LIFT_PRESET_HEIGHT_LOW;
		               	break;
			}
			//compare sensor value with preset value
			diff = targetHeightValue - SensorValue[liftHeight];
			//writeDebugStreamLine("height: %d - %d - %d liftMode:%d", diff,targetHeightValue,SensorValue[liftHeight],liftMode);
			//sleep(100);
			//if sensor show lift is lower by more than 50, go up fast
			if((diff > 50)&&(liftMode == automatic))
			{
				liftValue = -40;
			}
			//if sensor show lift is lower by less than 50, go up slow
			else if((diff < 50)&&(diff > 10)&&(liftMode == automatic))
			{
				liftValue = -20;
			}
			//if sensor show lift is high by more than 50, go down fast
			else if((diff < -50)&&(liftMode == automatic))
			{
				liftValue = 30;
			}
			//if sensor show lift is lower by less than 50, go down slow
			else if((diff > -50)&&(diff < -10)&&(liftMode == automatic))
			{
				liftValue = 20;
			}

			//writeDebugStreamLine("liftValue %d", liftValue);
			motor[liftPair1] = liftValue;
			motor[liftPair2] = liftValue;
			//##################################################################################

			//claw
			if ((vexRT[Btn6DXmtr2] == 1)&&(SensorValue[forkLiftPot] > 20))
			{
				clawDrive = -60;
			}
			else if ((vexRT[Btn6UXmtr2] == 1)&&(SensorValue[forkLiftPot] < 1500))
			{
		    clawDrive = 60;
			}
			else //all controls released
			{
				clawDrive = 0;
			}
			motor[claw] = clawDrive;
		}
		/////////////////////////////////////////////////////////////////////////////
		//Single user mode
		else
		{
			//drive
			motor[rightTrack] = vexRT[Ch2];
			motor[leftTrack] = vexRT[Ch3];

			////////////////////////////////////////////////////

			//lift progressive power
			if((vexRT[Btn5U] == 1)||(vexRT[Btn5D] == 1))
			{
				if(power < 126)
				{
					power = power + 1;
				}
			}
			//writeDebugStreamLine("power %d", power);

			//lift
			if(vexRT[Btn5U] == 1)
			{
				liftValue = power * -1;
			}
			else if(vexRT[Btn5D] == 1)
			{
				liftValue = power;

			}
			else
			{
				liftValue = 0;
				power = 0;
			}

			//writeDebugStreamLine("liftValue %d", liftValue);
			motor[liftPair1] = liftValue;
			motor[liftPair2] = liftValue;

			//claw
			if ((vexRT[Btn6D] == 1)&&(SensorValue[forkLiftPot] > 20))
			{
				clawDrive = -60;
			}
			else if ((vexRT[Btn6U] == 1)&&(SensorValue[forkLiftPot] < 1500))
			{
				clawDrive = 60;
			}
			else //all controls released
			{
				clawDrive = 0;
			}
			motor[claw] = clawDrive;

		}
		sleep(10);
	}
}
