#pragma config(Motor,  port2,           liftPair1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftPair2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           deployClaw,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           rightTrack,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftTrack,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#define HOLD_POWER 30

void pre_auton()
{
}

task autonomous()
{
	//auto Blue

 	//lift up body
	motor[liftPair1] = -40;
  motor[liftPair2] = -40;
  sleep(750);
	motor[liftPair1] = 0;
  motor[liftPair2] = 0;

//deploy claw
  motor[claw] = -127;
  sleep(3000);
  motor[claw] = 0;

 //lower body
 motor[liftPair1] = 40;
 motor[liftPair2] = 40;
 sleep(750);
 motor[liftPair1] = 0;
 motor[liftPair2] = 0;

  //move forward
	motor[rightTrack] = 60;
	motor[leftTrack] = 60;
	sleep(2100);
	motor[rightTrack] = 0;
	motor[leftTrack] = 0;

	//turn right
	motor[rightTrack] = -60;
	motor[leftTrack] = 60;
	sleep(1800);
	motor[rightTrack] = 0;
	motor[leftTrack] = 0;

	//to flag
	motor[rightTrack] = 60;
	motor[leftTrack] = 60;
	sleep(2800);
	motor[rightTrack] = 0;
	motor[leftTrack] = 0;

	/* auto Red
	//lift up
	motor[liftPair1] = -40;
  motor[liftPair2] = -40;
  sleep(750);
	motor[liftPair1] = 0;
  motor[liftPair2] = 0;

//deploy claw
  motor[claw] = -127;
  sleep(3000);
  motor[claw] = 0;

 //lower
 motor[liftPair1] = 40;
 motor[liftPair2] = 40;
 sleep(700);
 motor[liftPair1] = 0;
 motor[liftPair2] = 0;

  //move forward
	motor[rightTrack] = 60;
	motor[leftTrack] = 60;
	sleep(2050);
	motor[rightTrack] = 0;
	motor[leftTrack] = 0;

	//turn left
	motor[rightTrack] = 60;
	motor[leftTrack] = -60;
	sleep(900);
	motor[rightTrack] = 0;
	motor[leftTrack] = 0;

	//to flag
	motor[rightTrack] = 60;
	motor[leftTrack] = 60;
	sleep(2900);
	motor[rightTrack] = 0;
	motor[leftTrack] = 0;
	*/


 }//end autonomous


/////////////////////////////////////////////////////////////////////////////////////////
//
//																 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task user_c_bot()
{
	bool partnerMode = true;
	int power = 0;
	int liftValue = 0;
	int clawDrive = 0;
	bool liftHoldDown = false;
	bool liftHoldUp = false;
	bool clawHold = false;
	int count = 0;
	while(1)
	{
		//select partner or user mode
		if((vexRT[Btn7R] == 1)&&(vexRT[Btn7L] == 1)&&(partnerMode == true))
		{
			count = count + 1;
			//writeDebugStreamLine("count %d", count);
			if(count > 300)
			{
				motor[claw] = 50;
				sleep(50);
				motor[claw] = 0;
				sleep(50);
				partnerMode = false;
				writeDebugStreamLine("solo %d", count);
				count = 0;
			}
		}
		else if ((vexRT[Btn7R] == 1)&&(vexRT[Btn7L] == 1)&&(partnerMode == false))
		{
			count = count + 1;
			//writeDebugStreamLine("count %d", count);
			if(count > 300)
			{
				motor[claw] = -50;
				sleep(50);
				motor[claw] = 50;
				sleep(50);
				motor[claw] = -50;
				sleep(50);
				motor[claw] = 50;
				sleep(50);
				motor[claw] = 0;
				sleep(50);
				partnerMode = true;
				writeDebugStreamLine("partner %d", count);
				count = 0;
			}
		}

		if(partnerMode)
		{
			//lift
			//motor[liftPair1] = vexRT[Ch2Xmtr2];
			//motor[liftPair2] = vexRT[Ch2Xmtr2];

			//drive
			motor[rightTrack] = vexRT[Ch2];
			motor[leftTrack] = vexRT[Ch3];

			////////////////////////////////////////////////////

			//lift progressive power
			if((vexRT[Btn5UXmtr2] == 1)||(vexRT[Btn5DXmtr2] == 1))
			{
				if(power < 126)
				{
					power = power + 1;
				}
			}
			//writeDebugStreamLine("power %d", power);

			//lift
			if(vexRT[Btn5UXmtr2] == 1)
			{
				liftValue = power * -1;
				liftHoldDown = false;
				liftHoldUp = false;
			}
			else if(vexRT[Btn5DXmtr2] == 1)
			{
				liftValue = power;
				liftHoldDown = false;
				liftHoldUp = false;
			}
			else
			{
				if(!(liftHoldDown)&&!(liftHoldUp))
				{
					liftValue = 0;
					power = 0;
				}
			}

			//lift hold
			if(vexRT[Btn7UXmtr2] == 1)
			{
				liftHoldUp = true;
				liftHoldDown = false;
				liftValue = HOLD_POWER * -1;
			}
			else if(vexRT[Btn7DXmtr2] == 1)
			{
				liftHoldDown = true;
				liftHoldUp = false;
				liftValue = HOLD_POWER;
			}
			//writeDebugStreamLine("liftValue %d", liftValue);
			motor[liftPair1] = liftValue;
			motor[liftPair2] = liftValue;

			/////////////////////////////////////////
			//Deploy claw
			if((vexRT[Btn8L] == 1)||(vexRT[Btn8LXmtr2] == 1))
			{
				motor[deployClaw] = 127;
			}
			else if((vexRT[Btn8R] == 1)||(vexRT[Btn8RXmtr2] == 1))
			{
				motor[deployClaw] = -127;
			}
			else
			{
				motor[deployClaw] = 0;
			}

			//claw
			if (vexRT[Btn6DXmtr2] == 1)
			{
				clawDrive = -60;
				clawHold = false;
			}
			else if (vexRT[Btn6UXmtr2] == 1)	 /* manual drive open 6U */
			{
				clawDrive = 60;
				clawHold = false;
			}
			else if (vexRT[Btn8DXmtr2] == 1)
			{
				clawHold = true;
				clawDrive = 30;
			}
			else //all controls released
			{
				if(clawHold)
				{
					clawDrive = HOLD_POWER;
				}
				else
				{
					clawDrive = 0;
				}
			}
			motor[claw] = clawDrive;
		}
		/////////////////////////////////////////////////////////////////////////////
		//Single user mode
		else
		{
			//drive
			motor[rightTrack] = vexRT[Ch2];
			motor[leftTrack] = vexRT[Ch3];

			////////////////////////////////////////////////////

			//lift progressive power
			if((vexRT[Btn5U] == 1)||(vexRT[Btn5D] == 1))
			{
				if(power < 126)
				{
					power = power + 1;
				}
			}
			//writeDebugStreamLine("power %d", power);

			//lift
			if(vexRT[Btn5U] == 1)
			{
				liftValue = power * -1;
				liftHoldDown = false;
				liftHoldUp = false;
			}
			else if(vexRT[Btn5D] == 1)
			{
				liftValue = power;
				liftHoldDown = false;
				liftHoldUp = false;
			}
			else
			{
				if(!(liftHoldDown)&&!(liftHoldUp))
				{
					liftValue = 0;
					power = 0;
				}
			}

			//lift hold
			if(vexRT[Btn7U] == 1)
			{
				liftHoldUp = true;
				liftHoldDown = false;
				liftValue = HOLD_POWER * -1;
			}
			else if(vexRT[Btn7D] == 1)
			{
				liftHoldDown = true;
				liftHoldUp = false;
				liftValue = HOLD_POWER;
			}
			//writeDebugStreamLine("liftValue %d", liftValue);
			motor[liftPair1] = liftValue;
			motor[liftPair2] = liftValue;

			/////////////////////////////////////////
			//Deploy claw
			if(vexRT[Btn8L] == 1)
			{
				motor[deployClaw] = 127;
			}
			else if(vexRT[Btn8R] == 1)
			{
				motor[deployClaw] = -127;
			}
			else
			{
				motor[deployClaw] = 0;
			}

			//claw
			if (vexRT[Btn6D] == 1)
			{
				clawDrive = -60;
				clawHold = false;
			}
			else if (vexRT[Btn6U] == 1)	 /* manual drive open 6U */
			{
				clawDrive = 60;
				clawHold = false;
			}
			else if (vexRT[Btn8D] == 1)
			{
				clawHold = true;
				clawDrive = 30;
			}
			else //all controls released
			{
				if(clawHold)
				{
					clawDrive = HOLD_POWER;
				}
				else
				{
					clawDrive = 0;
				}
			}
			motor[claw] = clawDrive;

		}
		sleep(10);
	}
}



task usercontrol()
{
	// User control code here, inside the loop

	// This is the main execution loop for the user control program. Each time through the loop
	// your program should update motor + servo values based on feedback from the joysticks.

	// .....................................................................................
	// Insert user code here. This is where you use the joystick values to update your motors, etc.
	// .....................................................................................

	startTask(user_c_bot);
}
