#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,		 LineDetect,		 sensorLineFollower)
#pragma config(Sensor, in2,		 ClawPot,				 sensorPotentiometer)
#pragma config(Sensor, in3,		 L_pot,					 sensorPotentiometer)
#pragma config(Sensor, dgtl1,	 L_Encoder,			 sensorQuadEncoder)
#pragma config(Motor,	 port2,						FR,						 tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,	 port3,						BR,						 tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,	 port4,						BL,						 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port5,						FL,						 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port6,						L1,						 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port7,						L2,						 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port8,						C,						 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port9,						M,						 tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"		//Main competition background code...do not modify!

#define	CLAW_MODE_manual 0
#define	CLAW_MODE_pot 1
#define	CLAW_MODE_hold 2

short lineValue;
short liftValue;	 /* lift encoder bottom to top ~ 110 */
short lift_position;	/* potentiometer bottom 784 top 2485 Feb 17, 2017 */
short claw_mode =	 CLAW_MODE_manual;
short claw_position;	/* actual:	potentiometer reading wide 1400, closed 2780*/
short claw_goal;		/* latched actual:	potentiometer reading when 8R is pressed */
short claw_error;		/* difference between	 */
short claw_drive;
short m_drive;


/////////////////////////////////////////////////////////////////////////////////////////
//
//													Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	SensorValue[L_Encoder] = 0;	 // wrist encoder


	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//																 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................
	/* step 1 : move forward for 4 seconds - to the wall */
	/* todo:	add line sensor!!! */
	//	motor[T] = -30;
	SensorValue[L_Encoder] = 0;	 // wrist encoder
	motor[M] = 0;

#if 0
	motor[FL] = 127;
	motor[FR] = 127;
	motor[BL] = 127;
	motor[BR] = 127;
	waitInMilliseconds (3200);
	/* step 2:	back off the wall slightly */
	motor[FL] = -127;
	motor[FR] = -127;
	motor[BL] = -127;
	motor[BR] = -127;
	waitInMilliseconds (180);
#else

	// raise lift just a bit
	motor[L1] = 127;
	motor[L2] = 127;
	//	motor[L3] = 127;

	waitInMilliseconds (300);
	motor[L1] = 0;
	motor[L2] = 0;
	//	motor[L3] = 0;

	//go foward until gray is detected
	motor[FL] = 60;
	motor[FR] = 60;
	motor[BL] = 60;
	motor[BR] = 60;

	waitInMilliseconds (600);

	while (SensorValue[LineDetect] < 800)
	{
		//confirm we are in the grey
	}
	while (SensorValue[LineDetect] > 800)
	{
		//continue until white is detected
	}
	waitInMilliseconds (200);

	while (SensorValue[LineDetect] < 800)
	{
		//continue until gray is detected
	}
	waitInMilliseconds (200);
	motor[FL] = 45;
	motor[FR] = 45;
	motor[BL] = 45;
	motor[BR] = 45;

	while (SensorValue[LineDetect] > 800)
	{
		//continue until white is detected
	}

	// then stop!!!!

#endif

	/* step 3:	stop motor:	 lift up to knock off a star */
	motor[FL] = 0;
	motor[FR] = 0;
	motor[BL] = 0;
	motor[BR] = 0;

	waitInMilliseconds (400);
	motor[FL] = -45;
	motor[FR] = -45;
	motor[BL] = -45;
	motor[BR] = -45;

	waitInMilliseconds (200);
	motor[FL] = 0;
	motor[FR] = 0;
	motor[BL] = 0;
	motor[BR] = 0;


	resetTimer(T1);

	while (SensorValue[L_Encoder] < 1234)
	{
		motor[L1] = 127;
		motor[L2] = 127;
		//		motor[L3] = 127;
		waitInMilliseconds (20);
		// check for more than 4 seconds ( probably hung up )
		//	 then drop, back and up again
		if(getTimer(T1, seconds) > 4) /* FIXME - use encoder to detect stall!!! */
		{
			motor[L1] = -127;
			motor[L2] = -127;
			//			motor[L3] = -127;
			waitInMilliseconds (200);
			motor[L1] = 0;
			motor[L2] = 0;
			//			motor[L3] = 0;

			motor[FL] = -127;
			motor[FR] = -127;
			motor[BL] = -127;
			motor[BR] = -127;
			waitInMilliseconds (50);
			resetTimer(T1);
		}
	}

	waitInMilliseconds (200);
	{
		motor[L1] = -127;
		motor[L2] = -127;
		//		motor[L3] = -127;
	}
	waitInMilliseconds (1500);
	motor[FL] = -127;
	motor[FR] = -127;
	motor[BL] = -127;
	motor[BR] = -127;
	waitInMilliseconds (180);
	/* step 4:	back off ( shake off star? ) */
	motor[FL] = 0;
	motor[FR] = 0;
	motor[BL] = 0;
	motor[BR] = 0;
	waitInMilliseconds (1200);

	motor[L1] = 0;
	motor[L2] = 0;
	//	motor[L3] = 0;

	motor[FL] = -127;
	motor[FR] = -127;
	motor[BL] = -127;
	motor[BR] = -127;
	waitInMilliseconds (500);
	/* all motors off	 */
	motor[FL] = 0;
	motor[FR] = 0;
	motor[BL] = 0;
	motor[BR] = 0;
	allMotorsOff();
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//																 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////




/*	use this for autonomous control */
int covert_inches_to_encoders(int inches)
{
	/* ToDo - confirm circumference of wheel */
#define counts_per_revolution 627.2
#define wheel_circumference_inches 15

	int encoder_pulses = inches * counts_per_revolution / wheel_circumference_inches;
	return encoder_pulses;
}

#define MAX_MOTOR 127
#define MIN_MOTOR -127




task user_b_bot()
{
	/* the claw has a potentiometer for position "claw_position"
	*	 the claw will be opened and closed manually using button 6U (close) and 6D (open)
	*	 once in the closed position, button 8R will store the current position : "claw_goal"
	*	 then hold that position using closed loop control until 6U or 6D are pressed */

	short x1, x2;

	/* check battery leve */
	writeDebugStreamLine("backup battery level: %d milliVolts", BackupBatteryLevel);
	writeDebugStreamLine("main battery level: %d milliVolts", nAvgBatteryLevel);
	writeDebugStreamLine("main immediate battery level: %d milliVolts", nImmediateBatteryLevel);

	while(1)
	{
		/* allow left/right on 1 or 4 */
		x1 = abs(vexRT[Ch1]);
		x2 = abs(vexRT[Ch4]);
		if (x1>x2)
		{
			m_drive = abs(vexRT[Ch1]);
		}
		else
		{
			m_drive = -1* vexRT[Ch4];	 /* 1&4 controls are backwards */
		}

		if((m_drive > 20) || (m_drive < -20))
		{
			motor[M] = m_drive;

			motor[FL] = 0;
			motor[FR] = 0;
			motor[BL] = 0;
			motor[BR] = 0;

		}
		else
		{

			//Driving Motor Control - directly from the vex controller
			motor[FL] = vexRT[Ch3] / 1;
			motor[FR] = vexRT[Ch2] / 1;
			motor[BL] = vexRT[Ch3] / 1;
			motor[BR] = vexRT[Ch2] / 1;

			motor[M] = 0;

		}

		//		motor[L1] = vexRT[Btn5U] / 1;
		//		motor[L2] = vexRT[Btn5U] / 1;
		//		motor[C] = vexRT[Btn6U] / 1;

		claw_position = SensorValue[ClawPot];	 // claw potentiometer goes 0 to 4095
		lineValue = SensorValue[LineDetect];
		liftValue = SensorValue[L_Encoder];
		lift_position = SensorValue[L_pot];

		/* drive scissor lift - directly with button 5 U/D */
		if ((vexRT[Btn5U] == 1) && (SensorValue[L_Encoder] < 12345)) /* FIXME - change limit to encoder */
		{
			motor[L1] = 127;
			motor[L2] = 127;
			//			motor[L3] = 127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[L1] = -127;
			motor[L2] = -127;
			//			motor[L3] = -127;
		}
		else
		{
			motor[L1] = 0;
			motor[L2] = 0;
			//			motor[L3] = 0;
		}

		/***********************************************
		*****************			 claw			**************
		* Use button 6D/U to close/open the claw
		*
		* Use button 8R to put the claw into 'hold' mode
		*	 where it will use the potentiometer to maintain
		*	 the last position when 8R was pressed
		* Claw potentiometer wide open 1400, closed 2780 (Feb 17 2017)
		*********************************************/
		//		if (vexRT[Btn8R] == 1)	/* switch to 'pot' mode */
		//		{
		//			claw_mode =	 CLAW_MODE_pot;
		//			claw_position = SensorValue[ClawPot];
		//			claw_goal = claw_position;	/* actual:	potentiometer reading */
		//			writeDebugStreamLine("claw pot mode: %d", claw_goal);
		//		}
		if (vexRT[Btn8R] == 1)	/* switch to 'hold' mode */
		{
			claw_mode =	 CLAW_MODE_hold;
			motor[C] = 90;	/* ToDo - harder hold torque */
			writeDebugStreamLine("claw hold mode: %d", claw_goal);
		}
		else if (vexRT[Btn8L] == 1) /* switch to 'hold' mode */
		{
			claw_mode =	 CLAW_MODE_hold;
			motor[C] = 50;	/* ToDo - figure out a safe hold torque */
			writeDebugStreamLine("claw hold mode: %d", claw_goal);
		}
		//		else if (vexRT[Btn8U] == 1)	 /* manual drive open 8U */
		else if (vexRT[Btn6U] == 1)	 /* manual drive open 6U */
		{
			motor[C] = -80;
			claw_mode =	 CLAW_MODE_manual;
		}
		//		else if (vexRT[Btn8D] == 1)	 /* manual drive open 8D */
		else if (vexRT[Btn6D] == 1)	 /* manual drive open 6D */
		{
			motor[C] = 100;
			claw_mode =	 CLAW_MODE_manual;
		}
		else if (claw_mode == CLAW_MODE_manual)
		{
			motor[C] = 0;	 /* ToDo - do we want some hold drive? */
		}
		/*	if hold mode, then use the potentiometer to set the motor drive */
		else if (claw_mode ==	 CLAW_MODE_pot)
		{
			claw_error = (claw_position- claw_goal);
			claw_drive = claw_error / 4;
			if (claw_drive > MAX_MOTOR )	 /* limit check */
			{
				claw_drive = MAX_MOTOR;
			}
			else if (claw_drive < MIN_MOTOR )		/* limit check */
			{
				claw_drive = MIN_MOTOR;
			}
			/* now set the motor drive */
			motor[C] = claw_drive;
		} // end CLAW_MODE_HOLD

		wait1Msec(20);

	}	 // end while(1)
}	 // end task



task usercontrol()
{
	// User control code here, inside the loop

	// This is the main execution loop for the user control program. Each time through the loop
	// your program should update motor + servo values based on feedback from the joysticks.

	// .....................................................................................
	// Insert user code here. This is where you use the joystick values to update your motors, etc.
	// .....................................................................................

	startTask(user_b_bot); // Remove this function call once you have "real" code.
}
