#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    LineDetect,     sensorLineFollower)
#pragma config(Sensor, in2,    ClawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  Turret_limit,   sensorTouch)
#pragma config(Motor,  port1,           T,             tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           M,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           L1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           C,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           FR,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................
	/* step 1 : move forward for 4 seconds - to the wall */
	/* todo:  add line sensor!!! */
		motor[T] = -20;
	motor[FL] = 127;
	motor[FR] = 127;
	motor[BL] = 127;
	motor[BR] = 127;
	waitInMilliseconds (4000);
	/* step 2:  back off the wall slightly */
	motor[FL] = -127;
	motor[FR] = -127;
	motor[BL] = -127;
	motor[BR] = -127;
	waitInMilliseconds (175);
	/* step 3:  stop motor:  lift up to knock off a star */
	motor[L1] = 127;
	motor[L2] = 127;
	motor[FL] = 0;
	motor[FR] = 0;
	motor[BL] = 0;
	motor[BR] = 0;
	waitInMilliseconds (10000);
	/* step 4:  back off ( shake off star? ) */
	motor[T] = 127;
	waitInMilliseconds (2000);
	motor[L1] = 0;
	motor[L2] = 0;
	motor[FL] = -127;
	motor[FR] = -127;
	motor[BL] = -127;
	motor[BR] = -127;
	waitInMilliseconds (800);
	/* all motors off  */
	motor[FL] = 0;
	motor[FR] = 0;
	motor[BL] = 0;
	motor[BR] = 0;
	allMotorsOff();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////




/*  use this for autonomous control */
int covert_inches_to_encoders(int inches)
{
	/* ToDo - confirm circumference of wheel */
#define counts_per_revolution 627.2
#define wheel_circumference_inches 15

	int encoder_pulses = inches * counts_per_revolution / wheel_circumference_inches;
	return encoder_pulses;
}

#define MAX_MOTOR 127
#define MIN_MOTOR -127


#define	CLAW_MODE_manual 0
#define	CLAW_MODE_pot 1
#define	CLAW_MODE_hold 2


task user_b_bot()
{
	/* the claw has a potentiometer for position "claw_position"
	*  the claw will be opened and closed manually using button 6U (close) and 6D (open)
	*  once in the closed position, button 8R will store the current position : "claw_goal"
	*  then hold that position using closed loop control until 6U or 6D are pressed */

	short claw_mode =  CLAW_MODE_manual;
	short claw_position;	/* actual:  potentiometer reading */
	short claw_goal;    /* latched actual:  potentiometer reading when 8R is pressed */
	short claw_error;   /* difference between  */
	short claw_drive;
	short turret_limit_sw;


	/* check battery leve */
	writeDebugStreamLine("backup battery level: %d milliVolts", BackupBatteryLevel);
	writeDebugStreamLine("main battery level: %d milliVolts", nAvgBatteryLevel);
	writeDebugStreamLine("main immediate battery level: %d milliVolts", nImmediateBatteryLevel);

	while(1)
	{
		//Driving Motor Control - directly from the vex controller
		motor[FL] = vexRT[Ch3] / 1;
		motor[FR] = vexRT[Ch2] / 1;
		motor[BL] = vexRT[Ch3] / 1;
		motor[BR] = vexRT[Ch2] / 1;
		motor[M] = vexRT[Ch4] / 1;
		//		motor[L1] = vexRT[Btn5U] / 1;
		//		motor[L2] = vexRT[Btn5U] / 1;
		//		motor[C] = vexRT[Btn6U] / 1;

		claw_position = SensorValue[ClawPot];  // claw potentiometer goes 0 to 4095
		turret_limit_sw = SensorValue[Turret_limit];

		/* drive scissor lift - directly with button 5 U/D */
		if (vexRT[Btn5U] == 1)
		{
			motor[L1] = 127;
			motor[L2] = 127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[L1] = -127;
			motor[L2] = -127;
		}
		else
		{
			motor[L1] = 0;
			motor[L2] = 0;
		}

		/***********************************************
		*****************      claw     **************
		* Use button 6D/U to close/open the claw
		*
		* Use button 8R to put the claw into 'hold' mode
		*  where it will use the potentiometer to maintain
		*  the last position when 8R was pressed
		*********************************************/
		if (vexRT[Btn8R] == 1)	/* switch to 'pot' mode */
		{
			claw_mode =  CLAW_MODE_pot;
			claw_position = SensorValue[ClawPot];
			claw_goal = claw_position;	/* actual:  potentiometer reading */
			writeDebugStreamLine("claw pot mode: %d", claw_goal);
		}
		else if (vexRT[Btn8L] == 1)	/* switch to 'hold' mode */
		{
			claw_mode =  CLAW_MODE_hold;
			motor[C] = 60;	/* ToDo - figure out a safe hold torque */
			writeDebugStreamLine("claw hold mode: %d", claw_goal);
		}
		else if (vexRT[Btn8U] == 1)  /* manual drive closed 8U */
		{
			motor[C] = 100;
			claw_mode =  CLAW_MODE_manual;
		}
		else if (vexRT[Btn8D] == 1)  /* manual drive open 6D */
		{
			motor[C] = -80;
			claw_mode =  CLAW_MODE_manual;
		}
		else if (claw_mode == CLAW_MODE_manual)
		{
			motor[C] = 0;  /* ToDo - do we want some hold drive? */
		}
		/*  if hold mode, then use the potentiometer to set the motor drive */
		else if (claw_mode ==  CLAW_MODE_pot)
		{
			claw_error = (claw_position- claw_goal);
			claw_drive = claw_error / 4;
			if (claw_drive > MAX_MOTOR )   /* limit check */
			{
				claw_drive = MAX_MOTOR;
			}
			else if (claw_drive < MIN_MOTOR )   /* limit check */
			{
				claw_drive = MIN_MOTOR;
			}
			/* now set the motor drive */
			motor[C] = claw_drive;
		} // end CLAW_MODE_HOLD
		/**********************************************
		**********      turret              **********
		*  The turret needs to be 'deployed' at the
		*  start of the competition, and can then be
		*  left alone
		*  added limit switch for open - end of travel
		*  Fixme - need to add hold mode?
		*********************************************/

		if ((vexRT[Btn7U] == 1) && (SensorValue[Turret_limit] == 0))
		{
			motor[T] = 120;
		}
	  else if (vexRT[Btn7L] == 1)
		{
			motor[T] = 127;
		}
		else if (vexRT[Btn7D] == 1)
		{
			motor[T] = -120;
		}
		else if (SensorValue[Turret_limit] == 1)
		{
			motor[T] = 10
			;
		}
		else
		{
			motor[T] = 20;
		}

		wait1Msec(20);

	}  // end while(1)
}  // end task



task usercontrol()
{
	// User control code here, inside the loop

		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................

		startTask(user_b_bot); // Remove this function call once you have "real" code.
}
