#pragma config(Sensor, in1,    LineDetect,     sensorLineFollower)
#pragma config(Sensor, in2,    ClawPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    L_pot,          sensorPotentiometer)
#pragma config(Sensor, dgtl1,  L_Encoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  mode3,          sensorDigitalIn)
#pragma config(Sensor, dgtl8,  mode2,          sensorDigitalIn)
#pragma config(Sensor, dgtl9,  mode1,          sensorDigitalIn)
#pragma config(Sensor, dgtl10, LEDR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, LEDY,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, LEDG,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           BrFork,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           L1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           C,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           M,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BlFork,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"		//Main competition background code...do not modify!

#define	CLAW_MODE_manual 0
#define	CLAW_MODE_pot 1
#define	CLAW_MODE_hold 2
#define CLAW_MODE_closing 3
#define CLAW_MODE_auto_open 4

#define FORWARD 1
#define REVERSE 0




short lineValue;
short liftValue;	 /* lift encoder bottom to top ~ 110 */
short lift_position;	/* potentiometer bottom 784 top 2620 Feb 23, 2017 */
short claw_mode =	 CLAW_MODE_manual;
short claw_position;	/* actual:	potentiometer reading wide 1400, closed 2800*/
short claw_goal;		/* latched actual:	potentiometer reading when 8R is pressed */
short claw_error;		/* difference between	 */
short claw_drive;
short m_drive;
short mode_1, mode_2, mode_3;	 /* autonomous mode variables */

short gyroValue;

// short gyroGoal = 0;


#define	LIFT_pot_position_down 790
#define	LIFT_pot_position_deploy 1200
#define	LIFT_pot_position_top 2600

#define	CLAW_pot_open 1450
#define	CLAW_pot_half_open 2100
#define	CLAW_pot_closed 2750

/*	white reflects high and gives low value.	grey reflects less and gives high value */
/* FIXME - confirm values */
#define LINE_white 400
#define LINE_grey	 1200
#define LINE_threshold ((LINE_white + LINE_grey)/2)




/////////////////////////////////////////////////////////////////////////////////////////
//
//													Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	SensorValue[LEDG]=0; /* 0 is off, 1 is on */
	SensorValue[LEDR]=0;
	SensorValue[LEDY]=0;

	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
	SensorType[in4] = sensorNone;
	wait1Msec(1000);
	//Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
	SensorType[in4] = sensorGyro;
	wait1Msec(2000);
	SensorValue[in4] = 0;	 // zero gyro
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.

	mode_1 = SensorValue[mode1];
	mode_2 = SensorValue[mode2];
	mode_3 = SensorValue[mode3];

	/* let the LED's confirm the autonomous armed or not ... red is OFF!!! */
	if (mode_3 == 0)
	{
		SensorValue[LEDR]=1;
	}
	else
	{
		SensorValue[LEDY]=1;
	}


	bStopTasksBetweenModes = true;


	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//																 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................
	/* let the mode_1, mode_2 set the autonomous program;
	*	 1,2
	*	 1,1 start on left, pick up cube and deliver
	*	 1,0 start on right, pick up cube and deliver
	*	 0,1 start on left, pick up stars and deliver
	*	 0,0 start on right, pick up stars and deliver
	*	 let mode_3 = 0 be used to not do autonomous
	*/

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//																 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////


#if 0
/*	use this for autonomous control */
int covert_inches_to_encoders(int inches)
{
	/* ToDo - confirm circumference of wheel */
#define counts_per_revolution 627.2
#define wheel_circumference_inches 15

	int encoder_pulses = inches * counts_per_revolution / wheel_circumference_inches;
	return encoder_pulses;

#endif

#define MAX_MOTOR 127
#define MIN_MOTOR -127



	task user_b_bot()
	{
		/* the claw has a potentiometer for position "claw_position"
		*	 the claw will be opened and closed manually using button 6U (close) and 6D (open)
		*	 once in the closed position, button 8R will store the current position : "claw_goal"
		*	 then hold that position using closed loop control until 6U or 6D are pressed */

		short x1, x2;
		short LED_toggle = 0;

		SensorValue[LEDG]=1;  /* 0 is OFF, 1 is ON */
		SensorValue[LEDR]=0;
		SensorValue[LEDY]=0;


		/* check battery leve */
		writeDebugStreamLine("backup battery level: %d milliVolts", BackupBatteryLevel);
		writeDebugStreamLine("main battery level: %d milliVolts", nAvgBatteryLevel);
		writeDebugStreamLine("main immediate battery level: %d milliVolts", nImmediateBatteryLevel);

#if 0
		// For best sensor results, clear out the gyro and manually configure it at the begging of the code.
		// The Gyro is configured by default to provide values from 0 to -3600 for clockwise rotation,
		// and 0 to 3600 for counter-clockwise rotation
		//Adjust SensorScale to correct the scaling for your gyro
		//SensorScale[in4] = 260;
		//Adjust SensorFullCount to set the "rollover" point. A value of 3600 sets the rollover point to +/-3600
		//SensorFullCount[in4] = 3600;

		//Specify the number of degrees for the robot to turn (1 degree = 10, or 900 = 90 degrees)
		int degrees10 = 900;

		//Completely clear out any previous sensor readings by setting the port to "sensorNone"
		SensorType[in4] = sensorNone;
		wait1Msec(1000);
		//Reconfigure Analog Port 4 as a Gyro sensor and allow time for ROBOTC to calibrate it
		SensorType[in4] = sensorGyro;
		wait1Msec(2000);
		SensorValue[in4] = 0;	 // initialize gyro sensor value

		gyroValue = SensorValue[in4];
		//While the absolute value of the gyro is less than the desired rotation...
		//...continue turning clockwise
		motor[FL] = 30;
		motor[FR] = -30;
		motor[BL] = 30;
		motor[BR] = -30;
		while(gyroValue > -900)
		{
			gyroValue = SensorValue[in4];
			mode_1 = SensorValue[mode1];
			mode_2 = SensorValue[mode2];
			wait1Msec(2);
		}
		//brake
		motor[FL] = -5;
		motor[FR] = 5;
		motor[BL] = -5;
		motor[BR] = 5;
		wait1Msec(1000);

		//...continue turning counter clockwise
		motor[FL] = -30;
		motor[FR] = +30;
		motor[BL] = -30;
		motor[BR] = +30;
		/* turn back to 0 */
		while(gyroValue < 0)
		{
			gyroValue = SensorValue[in4];
			mode_1 = SensorValue[mode1];
			mode_2 = SensorValue[mode2];
			wait1Msec(1);
		}
		//brake
		motor[FL] = 5;
		motor[FR] = -5;
		motor[BL] = 5;
		motor[BR] = -5;
#endif
		//bool revDrive = false;
		int direction = FORWARD;

		while(1)
		{
			//delete sleep



			//lift


			if(vexRT[Btn8U] == 1)
			{

				motor[BlFork]=90;
				motor[BrFork]=-90;

			}
			else if(vexRT[Btn8D] == 1)
			{

				motor[BlFork]=-90;
				motor[BrFork]=90;

			}
			else{
				motor[BlFork]=0;
				motor[BrFork]=0;
			}






			//	sleep(50);

			if((direction == FORWARD)&&(vexRT[Btn7D] == 1))
			{
				direction = REVERSE;
			}
			else if((direction == REVERSE)&&(vexRT[Btn7U] == 1))
			{
				direction = FORWARD;
			}
			writeDebugStream("dir:%d\n",direction);


			/* heartbeat ... it's alive!!!! */
			if (LED_toggle++ == 10)
			{
				SensorValue[LEDG]=1;
			}
			else if (LED_toggle == 20)
			{
				SensorValue[LEDG]=0;
				LED_toggle = 0;
			}

			/* allow left/right on 1 or 4 */
			x1 = abs(vexRT[Ch1]);
			x2 = abs(vexRT[Ch4]);
			if (x1>x2)
			{
				m_drive = 1*vexRT[Ch1];
			}
			else
			{
				m_drive = 1* vexRT[Ch4];	 /* 1&4 controls are backwards */
			}

			if((m_drive > 125) || (m_drive < -125))
			{
				motor[M] = m_drive;

				motor[FL] = 0;
				motor[FR] = 0;
				motor[BL] = 0;
				motor[BR] = 0;

			}
			else
			{

				//Driving Motor Control - directly from the vex controller
				if(direction == FORWARD)
				{
					motor[FL] = vexRT[Ch3] / 1;
					motor[FR] = vexRT[Ch2] / 1;
					motor[BL] = vexRT[Ch3] / 1;
					motor[BR] = vexRT[Ch2] / 1;
					} else {


					motor[FL] = (vexRT[Ch2] / 1)* -1;
					motor[FR] = (vexRT[Ch3] / 1)* -1;
					motor[BL] = (vexRT[Ch2] / 1)* -1;
					motor[BR] = (vexRT[Ch3] / 1)* -1;

				}


				motor[M] = 0;


			}

			//		motor[L1] = vexRT[Btn5U] / 1;
			//		motor[L2] = vexRT[Btn5U] / 1;
			//		motor[C] = vexRT[Btn6U] / 1;

			claw_position = SensorValue[ClawPot];	 // claw potentiometer goes 0 to 4095
			lineValue = SensorValue[LineDetect];
			liftValue = SensorValue[L_Encoder];
			lift_position = SensorValue[L_pot];
			gyroValue = SensorValue[in4];

			/* drive scissor lift - directly with button 5 U/D */
			if ((vexRT[Btn5U] == 1) && (SensorValue[L_Encoder] < 12345)) /* FIXME - change limit to encoder */
			{
				motor[L1] = 127;
				motor[L2] = 127;
				//			motor[L3] = 127;
			}
			else if (vexRT[Btn5D] == 1)
			{
				motor[L1] = -127;
				motor[L2] = -127;
				//			motor[L3] = -127;
			}
			else
			{
				motor[L1] = 0;
				motor[L2] = 0;
				//			motor[L3] = 0;
			}

			/***********************************************
			*****************			 claw			**************
			* Use button 6D/U to close/open the claw
			*
			* Use button 8R to put the claw into 'hold' mode
			*	 where it will use the potentiometer to maintain
			*	 the last position when 8R was pressed
			* Claw potentiometer wide open 1400, closed 2780 (Feb 17 2017)
			*********************************************/
			//		if (vexRT[Btn8R] == 1)	/* switch to 'pot' mode */
			//		{
			//			claw_mode =	 CLAW_MODE_pot;
			//			claw_position = SensorValue[ClawPot];
			//			claw_goal = claw_position;	/* actual:	potentiometer reading */
			//			writeDebugStreamLine("claw pot mode: %d", claw_goal);
			//		}
			if (vexRT[Btn8R] == 1)	/* switch to 'hold' mode */
			{
				claw_mode =	 CLAW_MODE_hold;
				motor[C] = 60;	/* ToDo - harder hold torque */
				writeDebugStreamLine("claw hold mode: %d", claw_goal);
			}
			else if (vexRT[Btn8L] == 1) /* switch to 'hold' mode */
			{
				claw_mode =	 CLAW_MODE_hold;
				motor[C] = 40;	/* ToDo - figure out a safe hold torque */
				writeDebugStreamLine("claw hold mode: %d", claw_goal);
			}
			//		else if (vexRT[Btn8U] == 1)	 /* manual drive open 8U */
			else if (vexRT[Btn6U] == 1)	 /* manual drive open 6U */
			{
				motor[C] = -80;
				claw_mode =	 CLAW_MODE_manual;
			}
			//		else if (vexRT[Btn8D] == 1)	 /* manual drive close 8D */
			else if (vexRT[Btn6D] == 1)	 /* manual drive close 6D */
			{
				motor[C] = 80;
				claw_mode =	 CLAW_MODE_manual;
			}
			else if (claw_mode == CLAW_MODE_manual)
			{
				motor[C] = 0;	 /* ToDo - do we want some hold drive? */
			}
			/*	if hold mode, then use the potentiometer to set the motor drive */
			else if (claw_mode ==	 CLAW_MODE_pot)
			{
				claw_error = (claw_position- claw_goal);
				claw_drive = claw_error / 4;
				if (claw_drive > MAX_MOTOR )	 /* limit check */
				{
					claw_drive = MAX_MOTOR;
				}
				else if (claw_drive < MIN_MOTOR )		/* limit check */
				{
					claw_drive = MIN_MOTOR;
				}
				/* now set the motor drive */
				motor[C] = claw_drive;
			} // end CLAW_MODE_HOLD

			wait1Msec(20);

		}	 // end while(1)
	}	 // end task



	task usercontrol()
	{
		// User control code here, inside the loop

		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................

		startTask(user_b_bot);
	}
