//use #2 for scrimmage
#pragma config(Motor,  port1,           BL,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           S1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           S2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           W,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int wrist_up = 0;
	int elbow_up = 0;

	while(1 == 1)
	{
		motor[FL] = vexRT[Ch3] / 4;
		motor[FR] = vexRT[Ch2] / 1;
		motor[BL] = vexRT[Ch3] / 4;
		motor[BR] = vexRT[Ch2] / 1;
		motor[S1] = vexRT[Btn5U] / Btn5D;
		motor[S2] = vexRT[Btn5U] / Btn5D;
		motor[W] = vexRT[Btn6U] / Btn6D;
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[S1] = 127;
			motor[S2] = 127;//...raise the arm.
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[S1] = -127;
				motor[S2] = -127;
		}
		else                      		//Else (neither button is pressed)...
		{
			//motor[S1] = 0;
			//motor[S2] = 0; //...stop the gripper.//...lower the arm.
		}
		//if(vexRT[Btn6U] == 1)       	//If button 5U is pressed...
	//	{
		//	motor[S2] = 127;    	//...raise the arm.
	//	}
	//	else if(vexRT[Btn6D] == 1)  	//Else, if button 5D is pressed...
	//	{
	//		motor[S2] = -127;   	//...lower the arm.
//		}
//		else                      		//Else (neither button is pressed)...
	//	{

	//		motor[S2] = 0;    		//...stop the gripper.
	//	}
		if(vexRT[Btn6U])     // == 1)       	//If button 6U is pressed...
		{
			motor[W] = 127;    	//...raise the arm.
		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
		{
			motor[W] = -127;
		}
		else                      		//Else (neither button is pressed)...
		{
		//	motor[W] = 0;    		//...stop the gripper.
		}

		//...stop the arm.
	}
}



//...lower the arm.
//    ;multi potato drive

//Arm Control
// if(vexRT[Btn6U] == 1)
//{
//  motor[armMotor] = 40;
//}
//  else if(vexRT[Btn6D] == 1)
//{
//    motor[armMotor] = -40;
// }
//  else
//{
//  motor[armMotor] = 0;
