#pragma config(Sensor, dgtl1,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  right,          sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)


//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	SensorValue(left) = 0;
	SensorValue(right) =0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	while(true) {
		// .....................................................................................
		// Insert user code here.
		// .....................................................................................
		bMotorReflected[port1] = false;
		bMotorReflected[port10] = true;
		bMotorReflected[port2] = true;
		bMotorReflected[port8] = false;

		if (SensorValue[left] < 3000) {

			if (SensorValue[left] > SensorValue[right]){

				motor[port1] = 100; //left     //Was 100 on 12/20/12
				motor[port2] = 100;  //left    // Was 100 on 12/20/12
				motor[port8] = 127;  //right
				motor[port10] = 127; //right

			}
			else if (SensorValue[right] > SensorValue[left]){

				motor[port1] = 127;  //left
				motor[port2] = 127;  //left
				motor[port8] = 100;  //right
				motor[port10] = 100; //right
				motor[port9] = 100;  //right      //Was 100 on 12/20/12
				motor[port10] = 100; //right      //Was 100 on 12/20/12

			}

			else{
				motor[port1] = 127;  //left
				motor[port2] = 127;  //left
				motor[port8] = 127;  //right
				motor[port10] = 127; //right
			}

				motor[port2] = 127;  //left
				motor[port9] = 127;  //right
				motor[port10] = 127; //right
			}
		}
		else {
			motor[port1] = 0;
			motor[port2] = 0;
			motor[port8] = 0;
			motor[port10] = 0;
			motor[port1] = 0;
			motor[port2] = 0;
			motor[port9] = 0;
			motor[port10] = 0;

			//program b

			//diagonal = 1616.66666666...
			//

		}
		SensorValue(left) = 0;
		SensorValue(right) = 0;
		wait1Msec(1000);
if (SensorValue[left] <= 500) {
	motor[port1] = -100;
	motor[port2] = -100;
	motor[port9] = 100;
	motor[port10] = 100;
}
if( SensorValue[left] >= 500) {
	motor[port1] = 0;
	motor[port2] = 0;
	motor[port9] = 0;
	motor[port10] = 0;





		}
}
////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................


<<<<<<< .mine
		bMotorReflected[port1] = false;
		bMotorReflected[port10] = true;
		bMotorReflected[port2] = true;
		bMotorReflected[port8] = false;
=======
		bMotorReflected[port1] = false;
		bMotorReflected[port10] = true;
		bMotorReflected[port2] = true;
		bMotorReflected[port9] = false;
>>>>>>> .r46

		while (true)

		{

<<<<<<< .mine
			motor[port1] = vexRT[Ch3];
			motor[port2] = vexRT[Ch3];
			motor[port8] = vexRT[Ch2];
			motor[port10] = vexRT[Ch2];
=======
			motor[port1] = vexRT[Ch3];
			motor[port2] = vexRT[Ch3];
			motor[port9] = vexRT[Ch2];
			motor[port10] = vexRT[Ch2];
>>>>>>> .r46

<<<<<<< .mine
		}
=======
			// up and down
			if (vexRT[Btn8U] == 1)

			{
				motor[port5] = 127;
				motor[port6] = 127;
			}

			else if (vexRT[Btn8D] == 1)

			{
				motor[port5] = -127;
				motor[port6] = -127;
			}
			else
			{
				motor[port5] = 0;
				motor[port6] = 0;
			}
		//	if (SensorValue[touch] == 1)
		//	{
			//	motor[port7] = 0;
			//}

			//push out and in
			 if (vexRT[Btn8L] == 1)

			{
				motor[port7] = 127;
			}

			else	if (vexRT[Btn8R] == 1)

			{
				motor[port7] = -127;
			}
			else
			{
				motor[port7] = 0;
			}

			//claw
			if (vexRT[Btn7U] == 1)
			{
				motor[port3] = -127;
			}
			else
			{
				motor[port3] = 127;
			}
		}
>>>>>>> .r46
	}
}
