#pragma config(Sensor, in1,    Potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port4,           armMotor2,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{

    if(vexRT[Btn6U] == 1)
    {
      motor[armMotor] = 40;
      motor[armMotor2] = 40;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[armMotor] = -40;
      motor[armMotor2] = -40;
    }
    else
    {
    	motor[armMotor2] = 0;
    	motor[armMotor] = 0;
  	}



}
}
