#pragma config(Motor,  port2,           omnomnom,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
	motor(omnomnom)= 100;


}




}
