#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_inch)
#pragma config(Motor,  port2,           frontLeft,     tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           frontRight,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port4,           backLeft,      tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port5,           backRight,     tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	writeDebugStream(sonar);
	wait1Msec(1000);
	while(true){
		if(sonar <= 5) {
			motor[backLeft]  = 0;
			motor[frontLeft]  = 0;
			motor[backRight]  = 0;
			motor[backRight]  = 0;
		}
		else{
			motor[backLeft]  = 127;
			motor[frontLeft]  = 127;
			motor[backRight]  = 127;
			motor[backRight]  = 127;
		}
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

	while (true)
	{
		motor[frontLeft]  = vexRT[Ch3];
		motor[frontRight] = vexRT[Ch3];
		motor[backLeft]  = vexRT[Ch3];
		motor[backRight] = vexRT[Ch3];
	}
}
