#pragma config(Motor,  port1,           motor1,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

motor[motor1] = 127;

}
