#pragma config(Motor,  port1,           leftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	while (true)
	{
		motor[rightMotor]  = vexRT[Ch2]; //Left side of the robot is controlled by the left joystick, Y-axis
		motor[leftMotor] = vexRT[Ch3];
	}


}
