#pragma config(Motor,  port1,           leftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port8,           armLeft,       tmotorVex393, openLoop)
#pragma config(Motor,  port9,           armRight,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	while (true)
	{
		motor[rightMotor]  = vexRT[Ch2]; //Left side of the robot is controlled by the left joystick, Y-axis
		motor[leftMotor] = vexRT[Ch3];

				if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[armLeft] = 127;    	//...raise the arm.
			motor[armRight] = 127;
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[armLeft] = -127;   	//...lower the arm.
			motor[armRight] = -127;
		}

	}


}
