#pragma config(Motor,  port2,           frontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool strafeLeft=false;
	bool strafeRight=false;
	bool rotateLeft=false;
	bool rotateRight=false;

	while(true){
		//Update buttons
		strafeLeft=vexRT[Btn7L];
		strafeRight=vexRT[Btn7R];
		rotateLeft=vexRT[Btn8L];
		rotateRight=vexRT[Btn8R];

		//Set motor direction based on button
		if(strafeLeft){
			//Move straight to the left
			motor[frontLeft]  = 127;
			motor[frontRight] = -127;
			motor[backLeft]  = -127;
			motor[backRight] = 127;
		}
		else if(strafeRight){
			//Move straight to the right
			motor[frontLeft]  = -127;
			motor[frontRight] = 127;
			motor[backLeft]  = 127;
			motor[backRight] = -127;
		}

		else if(rotateRight){
			//Rotate Clockwise
			motor[frontLeft]  = 127;
			motor[frontRight] = -127;
			motor[backLeft]  = 127;
			motor[backRight] = -127;
		}

		else if(rotateLeft){
			//Rotate Counter-Clockwise
			motor[frontLeft]  = -127;
			motor[frontRight] = 127;
			motor[backLeft]  = -127;
			motor[backRight] = 127;
		}
		else{
			//Tank Drive
			motor[frontLeft]  = vexRT[Ch2];
			motor[frontRight] = vexRT[Ch3];
			motor[backLeft]  = vexRT[Ch2];
			motor[backRight] = vexRT[Ch3];
		}
	}
}
